# HGNC (Hugo Gene Nomenclature Committee) https://www.genenames.org/
# Via: https://www.genenames.org/download/custom/
# Downloaded URL: https://www.genenames.org/cgi-bin/download/custom?col=gd_hgnc_id&col=gd_app_sym&col=gd_prev_sym&col=gd_aliases&col=gd_pub_refseq_ids&col=gd_pub_ensembl_id&status=Approved&status=Entry%20Withdrawn&hgnc_dbtag=on&order_by=gd_app_sym_sort&format=text&submit=submit
- data_file: HGNC.tsv
  columns:
    Approved symbol: { namespace: HGNC }
    Previous symbols: { namespace: HGNC, is_alternative: true }
    Alias symbols: { namespace: HGNC, is_alternative: true }
    RefSeq IDs: { namespace: RefSeq }
    Ensembl gene ID: { namespace: Ensembl }
